services:

  postgres:
    image: postgres:17
    container_name: hts-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

volumes:
  postgres_data:

secrets:
  postgres_db:
    file: ../secrets/postgres_db.txt

  postgres_user:
    file: ../secrets/postgres_user.txt

  postgres_password:
    file: ../secrets/postgres_password.txt